// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg12slskOhpN6RFNJ6kn8ihhh8logFflU',
    appId: '1:982539506181:web:04712924490e72bd7b826c',
    messagingSenderId: '982539506181',
    projectId: 'spotify2002',
    authDomain: 'spotify2002.firebaseapp.com',
    storageBucket: 'spotify2002.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSnAWqHiNKhY8qd3Qsb1UwCHaxgnsjVrQ',
    appId: '1:982539506181:android:3eac50a0be03519e7b826c',
    messagingSenderId: '982539506181',
    projectId: 'spotify2002',
    storageBucket: 'spotify2002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqWPIzwobhommttfBE-IeRTOLbbkCk50',
    appId: '1:982539506181:ios:3e394e87eb1092e87b826c',
    messagingSenderId: '982539506181',
    projectId: 'spotify2002',
    storageBucket: 'spotify2002.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqWPIzwobhommttfBE-IeRTOLbbkCk50',
    appId: '1:982539506181:ios:3e394e87eb1092e87b826c',
    messagingSenderId: '982539506181',
    projectId: 'spotify2002',
    storageBucket: 'spotify2002.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg12slskOhpN6RFNJ6kn8ihhh8logFflU',
    appId: '1:982539506181:web:f8915dc11ef2700a7b826c',
    messagingSenderId: '982539506181',
    projectId: 'spotify2002',
    authDomain: 'spotify2002.firebaseapp.com',
    storageBucket: 'spotify2002.appspot.com',
  );
}
